// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nslkgzfrylrvutvebuez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zbGtnemZyeWxydnV0dmVidWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODYyOTcsImV4cCI6MjA2OTM2MjI5N30.m9QQfseI5wV8R_sF8bL76E7YlOh5xkforEdPpr02Bs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});